# Generated by Django 4.2.4 on 2023-08-30 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('tel', models.CharField(max_length=20)),
                ('yashash_joyi', models.CharField(max_length=100)),
                ('order_name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
