# Generated by Django 4.2.4 on 2023-08-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
    ]
