# Generated by Django 4.2.4 on 2023-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productsmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
